config/routes.rb
Rails.application.routes.draw do
  match '/404', to: 'not_found#builder', via: :all
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: 'api/v1', as: 'api' do
      resources :addresses

      resources :employees

    end
    mount VandalUi::Engine, at: '/vandal'
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "addresses#index"
  # Routes for the Address resource:

  # CREATE
  get("/addresses/new", { :controller => "addresses", :action => "new_form" })
  post("/create_address", { :controller => "addresses", :action => "create_row" })

  # READ
  get("/addresses", { :controller => "addresses", :action => "index" })
  get("/addresses/:id_to_display", { :controller => "addresses", :action => "show" })

  # UPDATE
  get("/addresses/:prefill_with_id/edit", { :controller => "addresses", :action => "edit_form" })
  post("/update_address/:id_to_modify", { :controller => "addresses", :action => "update_row" })

  # DELETE
  get("/delete_address/:id_to_remove", { :controller => "addresses", :action => "destroy_row" })
  get("/delete_address_from_employee/:id_to_remove", { :controller => "addresses", :action => "destroy_row_from_employee" })

  #------------------------------

  devise_for :employees
  # Routes for the Employee resource:

  # READ
  get("/employees", { :controller => "employees", :action => "index" })
  get("/employees/:id_to_display", { :controller => "employees", :action => "show" })

  #------------------------------

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_bootstrapcdn_assets.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" >

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissable" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissable" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <a class="navbar-brand" href="/">
      Mapmarkerissue
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links" aria-controls="collapsible-nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsible-nav-links">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="/addresses" class="dropdown-item">
              Addresses
            </a>
            <a href="/employees" class="dropdown-item">
              Employees
            </a>
            <a href="/rails_direct_uploads" class="dropdown-item">
              Rails Direct Uploads
            </a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_employee.blank? %>
          <li class="nav-item">
            <a href="/employees/sign_in" class="nav-link">
              Sign in
            </a>
          </li>

          <li class="nav-item">
            <a href="/employees/sign_up" class="nav-link">
              Sign up
            </a>
          </li>
        <% else %>
          <li class="nav-item">
            <a href="/employees/edit" class="nav-link">
              Edit profile
            </a>
          </li>

          <li class="nav-item">
            <a href="/employees/sign_out" data-method="delete" class="nav-link">
              Sign out
            </a>
          </li>
        <% end %>
      </ul>
</nav>